// Generated by https://quicktype.io
package types

type FPLCurrentPlayer struct {
	HistoryPast     []HistoryPast    `json:"history_past"`
	FixturesSummary []FixtureElement `json:"fixtures_summary"`
	Explain         []ExplainElement `json:"explain"`
	HistorySummary  []History        `json:"history_summary"`
	Fixtures        []FixtureElement `json:"fixtures"`
	History         []History        `json:"history"`
}

type ExplainElement struct {
	Explain ExplainExplain `json:"explain"`
	Fixture ExplainFixture `json:"fixture"`
}

type ExplainExplain struct {
	Bonus       Bonus `json:"bonus"`
	CleanSheets Bonus `json:"clean_sheets"`
	Saves       Bonus `json:"saves"`
	Minutes     Bonus `json:"minutes"`
}

type Bonus struct {
	Points int64  `json:"points"`
	Name   string `json:"name"`
	Value  int64  `json:"value"`
}

type ExplainFixture struct {
	ID                    int64             `json:"id"`
	KickoffTimeFormatted  string            `json:"kickoff_time_formatted"`
	Started               bool              `json:"started"`
	EventDay              int64             `json:"event_day"`
	DeadlineTime          string            `json:"deadline_time"`
	DeadlineTimeFormatted string            `json:"deadline_time_formatted"`
	Stats                 []map[string]Stat `json:"stats"`
	Code                  int64             `json:"code"`
	KickoffTime           string            `json:"kickoff_time"`
	TeamHScore            int64             `json:"team_h_score"`
	TeamAScore            int64             `json:"team_a_score"`
	Finished              bool              `json:"finished"`
	Minutes               int64             `json:"minutes"`
	ProvisionalStartTime  bool              `json:"provisional_start_time"`
	FinishedProvisional   bool              `json:"finished_provisional"`
	Event                 int64             `json:"event"`
	TeamA                 int64             `json:"team_a"`
	TeamH                 int64             `json:"team_h"`
}

type Stat struct {
	A []ValEl `json:"a"`
	H []ValEl `json:"h"`
}

type ValEl struct {
	Value   int64 `json:"value"`
	Element int64 `json:"element"`
}

type FixtureElement struct {
	ID                   int64       `json:"id"`
	KickoffTimeFormatted string      `json:"kickoff_time_formatted"`
	EventName            string      `json:"event_name"`
	OpponentName         string      `json:"opponent_name"`
	OpponentShortName    string      `json:"opponent_short_name"`
	IsHome               bool        `json:"is_home"`
	Difficulty           int64       `json:"difficulty"`
	Code                 int64       `json:"code"`
	KickoffTime          string      `json:"kickoff_time"`
	TeamHScore           interface{} `json:"team_h_score"`
	TeamAScore           interface{} `json:"team_a_score"`
	Finished             bool        `json:"finished"`
	Minutes              int64       `json:"minutes"`
	ProvisionalStartTime bool        `json:"provisional_start_time"`
	FinishedProvisional  bool        `json:"finished_provisional"`
	Event                int64       `json:"event"`
	TeamA                int64       `json:"team_a"`
	TeamH                int64       `json:"team_h"`
}

type History struct {
	ID                            int64  `json:"id"`
	KickoffTime                   string `json:"kickoff_time"`
	KickoffTimeFormatted          string `json:"kickoff_time_formatted"`
	TeamHScore                    int64  `json:"team_h_score"`
	TeamAScore                    int64  `json:"team_a_score"`
	WasHome                       bool   `json:"was_home"`
	Round                         int64  `json:"round"`
	TotalPoints                   int64  `json:"total_points"`
	Value                         int64  `json:"value"`
	TransfersBalance              int64  `json:"transfers_balance"`
	Selected                      int64  `json:"selected"`
	TransfersIn                   int64  `json:"transfers_in"`
	TransfersOut                  int64  `json:"transfers_out"`
	LoanedIn                      int64  `json:"loaned_in"`
	LoanedOut                     int64  `json:"loaned_out"`
	Minutes                       int64  `json:"minutes"`
	GoalsScored                   int64  `json:"goals_scored"`
	Assists                       int64  `json:"assists"`
	CleanSheets                   int64  `json:"clean_sheets"`
	GoalsConceded                 int64  `json:"goals_conceded"`
	OwnGoals                      int64  `json:"own_goals"`
	PenaltiesSaved                int64  `json:"penalties_saved"`
	PenaltiesMissed               int64  `json:"penalties_missed"`
	YellowCards                   int64  `json:"yellow_cards"`
	RedCards                      int64  `json:"red_cards"`
	Saves                         int64  `json:"saves"`
	Bonus                         int64  `json:"bonus"`
	Bps                           int64  `json:"bps"`
	Influence                     string `json:"influence"`
	Creativity                    string `json:"creativity"`
	Threat                        string `json:"threat"`
	ICTIndex                      string `json:"ict_index"`
	EaIndex                       int64  `json:"ea_index"`
	OpenPlayCrosses               int64  `json:"open_play_crosses"`
	BigChancesCreated             int64  `json:"big_chances_created"`
	ClearancesBlocksInterceptions int64  `json:"clearances_blocks_interceptions"`
	Recoveries                    int64  `json:"recoveries"`
	KeyPasses                     int64  `json:"key_passes"`
	Tackles                       int64  `json:"tackles"`
	WinningGoals                  int64  `json:"winning_goals"`
	AttemptedPasses               int64  `json:"attempted_passes"`
	CompletedPasses               int64  `json:"completed_passes"`
	PenaltiesConceded             int64  `json:"penalties_conceded"`
	BigChancesMissed              int64  `json:"big_chances_missed"`
	ErrorsLeadingToGoal           int64  `json:"errors_leading_to_goal"`
	ErrorsLeadingToGoalAttempt    int64  `json:"errors_leading_to_goal_attempt"`
	Tackled                       int64  `json:"tackled"`
	Offside                       int64  `json:"offside"`
	TargetMissed                  int64  `json:"target_missed"`
	Fouls                         int64  `json:"fouls"`
	Dribbles                      int64  `json:"dribbles"`
	Element                       int64  `json:"element"`
	Fixture                       int64  `json:"fixture"`
	OpponentTeam                  int64  `json:"opponent_team"`
}

type HistoryPast struct {
	ID              int64  `json:"id"`
	SeasonName      string `json:"season_name"`
	ElementCode     int64  `json:"element_code"`
	StartCost       int64  `json:"start_cost"`
	EndCost         int64  `json:"end_cost"`
	TotalPoints     int64  `json:"total_points"`
	Minutes         int64  `json:"minutes"`
	GoalsScored     int64  `json:"goals_scored"`
	Assists         int64  `json:"assists"`
	CleanSheets     int64  `json:"clean_sheets"`
	GoalsConceded   int64  `json:"goals_conceded"`
	OwnGoals        int64  `json:"own_goals"`
	PenaltiesSaved  int64  `json:"penalties_saved"`
	PenaltiesMissed int64  `json:"penalties_missed"`
	YellowCards     int64  `json:"yellow_cards"`
	RedCards        int64  `json:"red_cards"`
	Saves           int64  `json:"saves"`
	Bonus           int64  `json:"bonus"`
	Bps             int64  `json:"bps"`
	Influence       string `json:"influence"`
	Creativity      string `json:"creativity"`
	Threat          string `json:"threat"`
	ICTIndex        string `json:"ict_index"`
	EaIndex         int64  `json:"ea_index"`
	Season          int64  `json:"season"`
}
